const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const exists = (file) => fs.existsSync(path.join(root, file))

const app = JSON.parse(read('miniprogram/app.json'))
assert(app.pages.includes('pages/love-advisor/love-advisor'))
assert(app.pages.includes('pages/date-coordination/date-coordination'))

const indexWxml = read('miniprogram/pages/index/index.wxml')
const indexJs = read('miniprogram/pages/index/index.js')
assert(indexWxml.includes('AI恋爱助手'))
assert(indexJs.includes('/pages/love-advisor/love-advisor'))

const profileJs = read('miniprogram/pages/profile/profile.js')
assert(profileJs.includes('平台AI客服'))
assert(profileJs.includes('agentType=platform_service'))

const matchDetail = read('miniprogram/pages/match-detail/match-detail.wxml')
assert(matchDetail.includes('申请约会'))
assert(matchDetail.includes('由平台协助双方分别填写偏好') || matchDetail.includes('AI 协调员会记录申请'))
assert(matchDetail.includes('date-coordination'))
assert(!matchDetail.includes('申请官方奔现对接'))
assert(!matchDetail.includes('<view class="meet-title">奔现对接</view>'))

for (const page of ['love-advisor', 'date-coordination']) {
  for (const ext of ['js', 'json', 'wxml', 'wxss']) {
    assert(exists(`miniprogram/pages/${page}/${page}.${ext}`), `${page}.${ext} missing`)
  }
}

const loveWxml = read('miniprogram/pages/love-advisor/love-advisor.wxml')
const loveWxss = read('miniprogram/pages/love-advisor/love-advisor.wxss')
const loveJs = read('miniprogram/pages/love-advisor/love-advisor.js')
assert(loveWxml.includes('健康恋爱'))
assert(loveWxml.includes('信息有限'))
assert(loveWxml.includes('AI 生成内容｜对话回复由人工智能生成，仅供参考'))
assert(loveWxml.includes('class="love-ai-disclosure"'))
assert(loveWxml.includes('class="love-copy"'))
assert(loveWxml.indexOf('love-ai-disclosure') < loveWxml.indexOf('love-start'))
assert(loveJs.includes("url: '/pages/chat/chat?agentType=love_advisor'"))
assert(loveJs.includes('openConversation'))
assert(/\.love-hero[\s\S]*display:\s*flex/.test(loveWxss))
assert(/\.love-start[\s\S]*font-family:\s*inherit/.test(loveWxss))
assert(/\.love-start[\s\S]*position:\s*absolute/.test(loveWxss) === false)
assert(/\.love-ai-disclosure[\s\S]*font-weight:\s*600/.test(loveWxss))

assert(matchDetail.includes('AI 生成内容，仅供参考'))
assert(matchDetail.includes('class="ai-disclaimer"'))
assert(read('miniprogram/pages/chat/chat.wxml').includes('AI 生成回复仅供参考'))
const dateJs = read('miniprogram/pages/date-coordination/date-coordination.js')
const dateWxml = read('miniprogram/pages/date-coordination/date-coordination.wxml')
const dateWxss = read('miniprogram/pages/date-coordination/date-coordination.wxss')
const dateFormState = read('miniprogram/pages/date-coordination/formState.js')
const combined = `${dateJs}\n${dateWxml}\n${dateFormState}`
for (const field of [
  'availability',
  'areas',
  'activities',
  'budget',
  'payment_preference',
  'duration',
  'transport_constraints',
  'other_requirements',
  'share_message'
]) assert(combined.includes(field), `${field} missing`)

assert(dateWxml.includes('未来14天'))
assert(dateJs.includes("const { get, post, put }"))
assert(dateJs.includes('/invitation-response'))
assert(dateJs.includes('/proposals/${proposalId}/confirm'))
assert(dateJs.includes("respondToProposal('confirm')"))
assert(dateJs.includes("periods: ['afternoon']"))
assert(dateJs.includes("value: '咖啡', label: '☕ 咖啡'"))
assert(dateJs.includes("value: '散步', label: '🚶 散步'"))
assert(dateFormState.includes('areas: []'))
assert(dateJs.includes('this.launchOptions ='))
assert(dateJs.includes('this.launchOptions || {}'))
assert(dateJs.includes('refreshCoordination'))
assert(dateJs.includes('onShow()'))
assert(dateJs.includes('buildCoordinationDisplay'))
assert(dateJs.includes('startCoordinationPolling'))
assert(dateJs.includes('stopCoordinationPolling'))
assert(dateJs.includes('/retry-processing'))
assert(dateJs.includes("respondToProposal('reject')"))
assert(dateWxml.includes('coordinationDisplay.processing'))
assert(dateWxml.includes('coordinationDisplay.failed'))
assert(dateWxml.includes('coordinationDisplay.manualHandoff'))
assert(dateWxml.includes('刷新最新状态'))
assert(dateWxml.includes('重新处理'))
assert(dateWxml.includes('这个方案不合适，继续协调'))
assert(dateWxml.includes('可约时间段'))
assert(dateWxml.includes("coordination.status === 'collecting_initiator'"))
assert(dateWxml.includes('showApplicationForm'))
assert(dateWxml.includes('发送第一次约会邀请'))
assert(dateWxml.includes('提交我的安排'))
assert(dateWxml.includes('📅 可约时间'))
assert(dateWxml.includes('📍 偏好区域'))
assert(dateWxml.includes('🎯 活动偏好'))
assert(dateWxml.includes('💰 人均预算'))
assert(dateWxml.includes('🤝 费用方式'))
assert(dateWxml.includes('⏳ 可接受时长'))
assert(dateWxml.includes('接受完整方案'))
assert(dateWxml.includes('只调整部分安排'))
assert(dateWxml.includes('这次暂不方便'))
assert(dateWxml.includes('当前协调情况'))
assert(dateWxml.includes('AI 协调方案'))
assert(dateWxml.includes('约会邀请已发送'))
assert(dateJs.includes('showPreSubmitCoordinatorCard'))
assert(dateWxml.includes('showPreSubmitCoordinatorCard'))
assert(dateWxml.includes('提交约会邀请后'))
assert(dateWxml.includes('class="ai-disclosure"'))
assert(dateJs.includes("status === 'inviting_partner'"))
assert(dateJs.includes("['accept', 'coordinate', 'decline']"))
assert(dateJs.includes('invitation_version'))
assert(dateJs.includes('invitationCard.invitation_version'))
assert(dateJs.includes('STALE_INVITATION_VERSION'))
assert(dateJs.includes('INVITATION_ALREADY_RESPONDED'))
assert(dateJs.includes("decision === 'coordinate'"))
assert(dateWxml.includes('公共场所'))
assert(!dateWxml.includes('<text class="choice-tag"'), 'interactive choices must not use text nodes')
assert(dateWxml.includes('<view class="choice-tag {{selection.activities[item.value]'))
assert(dateWxml.includes("form.budget === item.value ? 'selected' : ''"))
assert(dateWxml.includes("form.payment_preference === item.value ? 'selected' : ''"))
assert(dateWxml.includes("form.duration === item.value ? 'selected' : ''"))
assert(dateWxml.includes('class="input field-input"'))
assert(dateWxml.includes('偏好区域（本次单选）'))
assert(dateWxml.includes('活动偏好（本次单选）'))
assert(dateWxml.includes('没有限制也可以留空'))
assert(dateWxml.includes('class="support-card support-card-ai"'))
assert(dateWxml.includes('class="support-card support-card-human"'))
assert(dateWxml.includes('AI约会协调员'))
assert(dateWxml.includes('人工客服协助'))
assert(dateWxss.includes('.choice-tag.selected'))
assert(dateWxss.includes('.support-card'))
assert(!/车牌|家庭住址|单位地址|是否开车/.test(combined))
assert(/loading|正在/.test(combined))
assert(/expired|已过期/.test(combined))
assert(/error|重试/.test(combined))

const chatJs = read('miniprogram/pages/chat/chat.js')
const requestJs = read('miniprogram/utils/request.js')
const waitingJs = read('miniprogram/utils/aiChatWaiting.js')
assert(exists('miniprogram/utils/aiChatWaiting.js'))
assert(chatJs.includes('aiChatWaiting'))
assert(chatJs.includes('runAssistantTurn'))
assert(chatJs.includes('retryAiMessage'))
assert(chatJs.includes('fetchCompleteAssistantReply'))
assert(chatJs.includes('clearWaitingTimers'))
assert(chatJs.includes('startHistoryPolling'))
assert(chatJs.includes('refreshAgentHistory'))
assert(chatJs.includes('stopHistoryPolling'))
assert(waitingJs.includes('extractReplyContent'))
assert(chatJs.includes('decodeURIComponent'))
assert(chatJs.includes("err && err.message"))
assert(waitingJs.includes("DATE_COORDINATOR: 'date_coordinator'"))
assert(chatJs.includes('AGENT_TYPES.DATE_COORDINATOR'))
assert(chatJs.includes('coordination_id: this.data.coordinationId'))
assert(chatJs.includes('resolveCompleteAssistantReply'))
assert(chatJs.includes('evaluateAssistantReply'))
assert(!chatJs.includes('感谢你的咨询，我会在信息范围内尽力协助。'))
assert(waitingJs.includes('evaluateAssistantReply'))
assert(waitingJs.includes('resolveCompleteAssistantReply'))
assert(dateJs.includes('agentType=date_coordinator'))
assert(dateJs.includes('INVITATION_EXPIRED'))
assert(dateJs.includes('本次约会邀请已结束，请查看最新状态。'))
assert(/async respondToProposal\(decision\)[\s\S]*?\/proposals\/\$\{proposalId\}\/confirm[\s\S]*?if \(decision === 'reject'\) this\.goCoordinator\(\)/.test(dateJs))
assert(chatJs.includes('patch_preview'))
assert(chatJs.includes('requires_confirmation'))
assert(chatJs.includes('/application-patches/${patchId}/${action}'))
assert(chatJs.includes('onConfirmPatch'))
assert(chatJs.includes('onCancelPatch'))
assert(chatJs.includes("submitPatchAction(e, 'confirm')"))
assert(chatJs.includes("submitPatchAction(e, 'cancel')"))
assert(chatJs.includes('INVITATION_ALREADY_RESPONDED'))
assert(chatJs.includes('STALE_INVITATION_VERSION'))
assert(chatJs.includes('INVITATION_EXPIRED'))
assert(chatJs.includes('PRIMARY_RESOLUTION_REQUIRED'))
assert(chatJs.includes('本次约会邀请已结束，请查看最新状态。'))
assert(chatJs.includes('onSelectPrimaryResolution'))
assert(chatJs.includes('primary_selection'))
assert(chatJs.includes('协调状态刚刚发生变化，请查看最新进度。'))
assert(chatJs.includes('patchSubmitting'))
assert(chatJs.includes('修改已确认'))
assert(chatJs.includes('暂不修改'))
assert(chatJs.includes("operation: patch.operation || 'modify'"))
assert(chatJs.includes("currentPreview.operation === 'create'"))
assert(chatJs.includes('API_PATHS.USER_PROFILE'))
assert(chatJs.includes('loadSupportCode'))
assert(chatJs.includes('retrySupportCode'))
assert(chatJs.includes('copySupportCode'))
assert(chatJs.includes('wx.setClipboardData'))
assert(chatJs.includes('/^WF-\\d{6}$/'))
assert(!/\bopenid\b/i.test(chatJs))
assert(!/\bphone\b/i.test(chatJs))
assert(dateJs.includes('arrival_position'))
assert(dateJs.includes("submitMeetingAction('arrived', { arrival_position:"))
assert(dateWxml.includes('初步会合范围（选填）'))
assert(!dateWxml.includes('class="form-label required">公共集合点'))

const chatWxml = read('miniprogram/pages/chat/chat.wxml')
assert(chatWxml.includes('用户ID'))
assert(chatWxml.includes('{{supportCode}}'))
assert(chatWxml.includes('bindtap="copySupportCode"'))
assert(chatWxml.includes('bindtap="retrySupportCode"'))
assert(chatWxml.includes('向客服提供此编号'))
assert(chatWxml.includes('msg-bubble-generating'))
assert(chatWxml.includes('AI生成中'))
assert(chatWxml.includes('retryAiMessage'))
assert(chatWxml.includes("item.status === 'generating'"))
assert(chatWxml.includes("item.status === 'error'"))
assert(chatWxml.includes("item.status === 'completed' && item.patchPreview"))
assert(chatWxml.includes('修改前'))
assert(chatWxml.includes('修改后'))
assert(chatWxml.includes('影响现有方案'))
assert(chatWxml.includes('将通知对方'))
assert(chatWxml.includes('确认修改'))
assert(chatWxml.includes("item.patchPreview.operation === 'create'"))
assert(chatWxml.includes('{{item.patchPreview.title}}'))
assert(chatJs.includes("'局部调整确认'"))
assert(chatJs.includes("'约会安排发送预览'"))
assert(chatJs.includes("'确认这些调整'"))
assert(chatWxml.includes('确认发送'))
assert(chatWxml.includes('暂不发送'))
assert(chatWxml.includes('bindtap="onConfirmPatch"'))
assert(chatWxml.includes('bindtap="onCancelPatch"'))
assert(chatWxml.includes('item.patchPreview.requiresConfirmation'))
assert(chatWxml.includes('item.patchPreview.primaryResolutionRequired'))
assert(chatWxml.includes('bindtap="onSelectPrimaryResolution"'))
assert(chatWxml.includes('本次建议'))
assert(chatWxml.includes('保留当前协调进度'))
assert(!chatWxml.includes('loading="{{sending}}"'))
assert(!chatWxml.includes('<text class="choice-tag"'))
assert(!chatWxml.includes('<text>{{item.patchPreview}}</text>'))

const chatWxss = read('miniprogram/pages/chat/chat.wxss')
assert(chatWxss.includes('.user-id-bar'))
assert(chatWxss.includes('.patch-preview-card'))
assert(chatWxss.includes('.primary-choice'))
assert(chatWxss.includes('flex-direction: column'))
assert(chatWxss.includes('overflow-wrap: anywhere'))
assert(chatWxss.includes('#fff0f4'))
assert(chatWxss.includes('gen-spin'))
assert(chatWxss.includes('msg-bubble-reveal'))
assert(requestJs.includes('功能服务尚未更新，请稍后再试'))
assert(requestJs.includes('功能数据正在初始化，请稍后再试'))

console.log('PASS agent mini program UI contract')
