module.exports = {
  user: 'users',
  user_match_setting: 'user_match_settings',
  user_match_log: 'user_match_logs',
  occupation_circle: 'occupation_circles',
  user_order: 'user_orders',
  marry_report: 'marry_reports',
  system_stat: 'system_stats',
  system_config: 'system_configs',
  ai_chat_log: 'ai_chat_logs',
  ai_knowledge: 'ai_knowledge',
  meet_report: 'meet_reports',
  meet_location_log: 'meet_location_logs',
  sos_log: 'sos_logs',
  free_whitelist: 'free_whitelist',
  free_whitelist_import_batch: 'free_whitelist_import_batches',
  match_handoff_ticket: 'match_handoff_tickets',
  partner: 'partners',
  partner_withdraw: 'partner_withdrawals',
  admin: 'admins',
  openid_blacklist: 'openid_blacklist',
  user_privacy_auth_log: 'user_privacy_auth_logs',
  partner_user_audit_log: 'partner_user_audit_logs',
  member_application: 'member_applications',
  ai_report_task: 'ai_report_tasks'
}
